name: Sync data.json

on:
  workflow_dispatch:

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0  # Fetch all branches

    - name: Fetch all branches
      run: git fetch --all

    - name: Checkout master branch
      run: git checkout master

    - name: Copy data.json to master branch
      run: |
        cp output/data.json .
        git add data.json
        git commit -m 'Sync data.json from main to master'
        git push origin master
