name: Sync data.json to master on changes and manual trigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Checkout master branch
      uses: actions/checkout@v3
      with:
        ref: master
        path: 'master-branch'

    - name: Ensure master branch directory exists
      run: |
        mkdir -p master-branch/output

    - name: Check if data.json exists and copy to master branch
      id: check_data_json
      run: |
        if [ -f output/data.json ]; then
          cp output/data.json master-branch/output/data.json
          echo "::set-output name=data_exists::true"
        else
          echo "::set-output name=data_exists::false"
        fi

    - name: Commit and push changes to master branch
      if: steps.check_data_json.outputs.data_exists == 'true'
      run: |
        cd master-branch
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/data.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Sync data.json from main to master"
        git push
