name: Sync data.json to master on changes and manual trigger

on:
  push:
    branches: 
      - main
  workflow_dispatch: 

jobs:
  sync:
    runs-on: ubuntu-latest 
    steps:
   
    - name: Checkout main branch
      uses: actions/checkout@v3 
      with: 
        ref: main

    
   
    - name: Checkout master branch
      uses: actions/checkout@v3
      with: 
        ref: master 
        path: 'master-branch' 
        fetch-depth: 0 # 确保获取 master 分支的完整历史记录，保持代码库一致性，确保数据完整

    - name: Ensure master branch directory exists
      run: |
        mkdir -p master-branch/output

    - name: Copy or replace data.json to master branch
      run: |
        cp output/data.json master-branch/output/data.json

    - name: Commit and push changes to master branch
      run: |
        cd master-branch
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/data.json
        if git diff --quiet && git diff --staged --quiet; then
          echo "No changes detected in data.json"
        else
          git commit -m "Sync data.json from main to master"
          git push
        fi
