name: Sync Data
on:
  push:
    paths:
      - 'output/data.json'
  workflow_dispatch:
jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Copy data.json to master branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git config pull.rebase true
          git checkout -b master || git checkout master
          mkdir -p output
          echo "Copying data.json from main to temporary location"
          cp output/data.json /tmp/data.json
          git checkout master
          mkdir -p output
          echo "Copying data.json from temporary location to master"
          cp /tmp/data.json output/data.json
          echo "Adding data.json to git"
          git add output/data.json
          echo "Committing changes"
          git commit -m "Update data.json from main branch" || echo "No changes to commit"
          echo "Pulling latest changes from remote master"
          git pull origin master --rebase || (git rebase --abort && git pull origin master)
          echo "Resolving conflicts"
          git add output/data.json
          git rebase --continue || echo "No more conflicts to resolve"
          echo "Pushing changes to master"
          git push origin master || echo "Nothing to push"
