name: Sync data.json to master on changes and manual trigger

on:
  push:
    branches: # 触发条件：当main分支有push事件
      - main
  workflow_dispatch: #手动触发

jobs:
  sync:
    runs-on: ubuntu-latest # 指定运行环境，可以是ubuntu windows macos，一般使用ubuntu-latest。常规配置
    steps:
    #确保工作流可以访问main分支
    - name: Checkout main branch
      uses: actions/checkout@v3 # 一般使用最新版本。版本查看 https://github.com/actions/checkout/releases
      with: #这是向上一步 actions/checkout@v3 传递身份令牌参数
        ref: main

    #确保工作流可以访问master分支
    # 将master检出到 master-branch 是防止文件冲突
    - name: Checkout master branch
      uses: actions/checkout@v3
      with: #这是向上一步 actions/checkout@v3 传递身份令牌参数
        ref: master 
        path: 'master-branch' # 这是一个基于GitHub Actions runs-on: ubuntu-latest 的虚拟的工作目录，只存在于虚拟环境中
        fetch-depth: 0 # 确保获取 master 分支的完整历史记录，保持代码库一致性，确保数据完整

    - name: Ensure master branch directory exists
      run: |
        mkdir -p master-branch/output

    - name: Copy or replace data.json to master branch
      run: |
        cp output/data.json master-branch/output/data.json

    #将更新后的data.json，推送到github
    - name: Commit and push changes to master branch
      run: |
        cd master-branch
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/data.json
        if git diff --quiet && git diff --staged --quiet; then
          echo "No changes detected in data.json"
        else
          git commit -m "Sync data.json from main to master"
          git push
        fi
