name: Sync Data

on:
  push:
    branches:
      - main

jobs:
  sync-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Copy data.json to master branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout master
          cp data.json path/to/master/index.html
          git add path/to/master/index.html
          git commit -m "Update data.json from main branch"
          git push origin master
